{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.targetName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "go-node-agent.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "5m" }}
  secretStoreRef:
    name: {{ .Values.externalSecret.storeName | default "vault" }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecret.targetName }}
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ .Values.externalSecret.vaultPath }}
        metadataPolicy: None
{{- end }}
