{{- if and .Values.service.enabled .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "go-node-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "go-node-agent.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "go-node-agent.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval | default "30s" }}
      scheme: http
{{- end }}
