apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "go-node-agent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "go-node-agent.labels" . | nindent 4 }}
automountServiceAccountToken: false
