image:
  repository: harbor.lannister-dev.ru/vpn-service/go-node-agent
  tag: prod
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: harbor-registry

nodeSelector:
  role: vpn
  channel: prod

env:
  controlApiURL: http://control-api.vpn-prod.svc.cluster.local:8000
  natsURL: nats://nats.nats.svc.cluster.local:4222
  nodeRole: entry
  logLevel: info
  logFormat: json
  heartbeatInterval: 10s

secrets:
  bootstrapTokenSecretName: go-node-agent-prod-bootstrap
  bootstrapTokenSecretKey: token

externalSecret:
  enabled: true
  storeName: vault
  vaultPath: go-node-agent/prod/env
  targetName: go-node-agent-prod-bootstrap
  refreshInterval: 5m

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"
  prometheus.io/path: "/metrics"
  prometheus-env: prod
  prometheus-app: go-node-agent

executor:
  enabled: false
