// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: vpn/agent/v1/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DesiredState int32

const (
	DesiredState_DESIRED_STATE_UNSPECIFIED DesiredState = 0
	DesiredState_DESIRED_STATE_ACTIVE      DesiredState = 1
	DesiredState_DESIRED_STATE_INACTIVE    DesiredState = 2
)

// Enum value maps for DesiredState.
var (
	DesiredState_name = map[int32]string{
		0: "DESIRED_STATE_UNSPECIFIED",
		1: "DESIRED_STATE_ACTIVE",
		2: "DESIRED_STATE_INACTIVE",
	}
	DesiredState_value = map[string]int32{
		"DESIRED_STATE_UNSPECIFIED": 0,
		"DESIRED_STATE_ACTIVE":      1,
		"DESIRED_STATE_INACTIVE":    2,
	}
)

func (x DesiredState) Enum() *DesiredState {
	p := new(DesiredState)
	*p = x
	return p
}

func (x DesiredState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DesiredState) Descriptor() protoreflect.EnumDescriptor {
	return file_vpn_agent_v1_agent_proto_enumTypes[0].Descriptor()
}

func (DesiredState) Type() protoreflect.EnumType {
	return &file_vpn_agent_v1_agent_proto_enumTypes[0]
}

func (x DesiredState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DesiredState.Descriptor instead.
func (DesiredState) EnumDescriptor() ([]byte, []int) {
	return file_vpn_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

type AppliedState int32

const (
	AppliedState_APPLIED_STATE_UNSPECIFIED AppliedState = 0
	AppliedState_APPLIED_STATE_PENDING     AppliedState = 1
	AppliedState_APPLIED_STATE_APPLIED     AppliedState = 2
	AppliedState_APPLIED_STATE_ERROR       AppliedState = 3
)

// Enum value maps for AppliedState.
var (
	AppliedState_name = map[int32]string{
		0: "APPLIED_STATE_UNSPECIFIED",
		1: "APPLIED_STATE_PENDING",
		2: "APPLIED_STATE_APPLIED",
		3: "APPLIED_STATE_ERROR",
	}
	AppliedState_value = map[string]int32{
		"APPLIED_STATE_UNSPECIFIED": 0,
		"APPLIED_STATE_PENDING":     1,
		"APPLIED_STATE_APPLIED":     2,
		"APPLIED_STATE_ERROR":       3,
	}
)

func (x AppliedState) Enum() *AppliedState {
	p := new(AppliedState)
	*p = x
	return p
}

func (x AppliedState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AppliedState) Descriptor() protoreflect.EnumDescriptor {
	return file_vpn_agent_v1_agent_proto_enumTypes[1].Descriptor()
}

func (AppliedState) Type() protoreflect.EnumType {
	return &file_vpn_agent_v1_agent_proto_enumTypes[1]
}

func (x AppliedState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AppliedState.Descriptor instead.
func (AppliedState) EnumDescriptor() ([]byte, []int) {
	return file_vpn_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

type ReportStatus int32

const (
	ReportStatus_REPORT_STATUS_UNSPECIFIED        ReportStatus = 0
	ReportStatus_REPORT_STATUS_APPLIED            ReportStatus = 1
	ReportStatus_REPORT_STATUS_PENDING            ReportStatus = 2
	ReportStatus_REPORT_STATUS_ERROR              ReportStatus = 3
	ReportStatus_REPORT_STATUS_SKIPPED_STALE      ReportStatus = 4
	ReportStatus_REPORT_STATUS_SKIPPED_IDEMPOTENT ReportStatus = 5
)

// Enum value maps for ReportStatus.
var (
	ReportStatus_name = map[int32]string{
		0: "REPORT_STATUS_UNSPECIFIED",
		1: "REPORT_STATUS_APPLIED",
		2: "REPORT_STATUS_PENDING",
		3: "REPORT_STATUS_ERROR",
		4: "REPORT_STATUS_SKIPPED_STALE",
		5: "REPORT_STATUS_SKIPPED_IDEMPOTENT",
	}
	ReportStatus_value = map[string]int32{
		"REPORT_STATUS_UNSPECIFIED":        0,
		"REPORT_STATUS_APPLIED":            1,
		"REPORT_STATUS_PENDING":            2,
		"REPORT_STATUS_ERROR":              3,
		"REPORT_STATUS_SKIPPED_STALE":      4,
		"REPORT_STATUS_SKIPPED_IDEMPOTENT": 5,
	}
)

func (x ReportStatus) Enum() *ReportStatus {
	p := new(ReportStatus)
	*p = x
	return p
}

func (x ReportStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReportStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_vpn_agent_v1_agent_proto_enumTypes[2].Descriptor()
}

func (ReportStatus) Type() protoreflect.EnumType {
	return &file_vpn_agent_v1_agent_proto_enumTypes[2]
}

func (x ReportStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReportStatus.Descriptor instead.
func (ReportStatus) EnumDescriptor() ([]byte, []int) {
	return file_vpn_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

type Protocol int32

const (
	Protocol_PROTOCOL_UNSPECIFIED Protocol = 0
	Protocol_PROTOCOL_VLESS       Protocol = 1
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "PROTOCOL_VLESS",
	}
	Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED": 0,
		"PROTOCOL_VLESS":       1,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_vpn_agent_v1_agent_proto_enumTypes[3].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_vpn_agent_v1_agent_proto_enumTypes[3]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_vpn_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

type TransportKind int32

const (
	TransportKind_TRANSPORT_KIND_UNSPECIFIED TransportKind = 0
	TransportKind_TRANSPORT_KIND_WS          TransportKind = 1
	TransportKind_TRANSPORT_KIND_XHTTP       TransportKind = 2
	TransportKind_TRANSPORT_KIND_TCP         TransportKind = 3
	TransportKind_TRANSPORT_KIND_REALITY     TransportKind = 4
)

// Enum value maps for TransportKind.
var (
	TransportKind_name = map[int32]string{
		0: "TRANSPORT_KIND_UNSPECIFIED",
		1: "TRANSPORT_KIND_WS",
		2: "TRANSPORT_KIND_XHTTP",
		3: "TRANSPORT_KIND_TCP",
		4: "TRANSPORT_KIND_REALITY",
	}
	TransportKind_value = map[string]int32{
		"TRANSPORT_KIND_UNSPECIFIED": 0,
		"TRANSPORT_KIND_WS":          1,
		"TRANSPORT_KIND_XHTTP":       2,
		"TRANSPORT_KIND_TCP":         3,
		"TRANSPORT_KIND_REALITY":     4,
	}
)

func (x TransportKind) Enum() *TransportKind {
	p := new(TransportKind)
	*p = x
	return p
}

func (x TransportKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransportKind) Descriptor() protoreflect.EnumDescriptor {
	return file_vpn_agent_v1_agent_proto_enumTypes[4].Descriptor()
}

func (TransportKind) Type() protoreflect.EnumType {
	return &file_vpn_agent_v1_agent_proto_enumTypes[4]
}

func (x TransportKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransportKind.Descriptor instead.
func (TransportKind) EnumDescriptor() ([]byte, []int) {
	return file_vpn_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

type SnapshotRequestReason int32

const (
	SnapshotRequestReason_SNAPSHOT_REQUEST_REASON_UNSPECIFIED     SnapshotRequestReason = 0
	SnapshotRequestReason_SNAPSHOT_REQUEST_REASON_STARTUP         SnapshotRequestReason = 1
	SnapshotRequestReason_SNAPSHOT_REQUEST_REASON_XRAY_RESTART    SnapshotRequestReason = 2
	SnapshotRequestReason_SNAPSHOT_REQUEST_REASON_REDELIVERY_GAP  SnapshotRequestReason = 3
	SnapshotRequestReason_SNAPSHOT_REQUEST_REASON_OPERATOR_FORCED SnapshotRequestReason = 4
)

// Enum value maps for SnapshotRequestReason.
var (
	SnapshotRequestReason_name = map[int32]string{
		0: "SNAPSHOT_REQUEST_REASON_UNSPECIFIED",
		1: "SNAPSHOT_REQUEST_REASON_STARTUP",
		2: "SNAPSHOT_REQUEST_REASON_XRAY_RESTART",
		3: "SNAPSHOT_REQUEST_REASON_REDELIVERY_GAP",
		4: "SNAPSHOT_REQUEST_REASON_OPERATOR_FORCED",
	}
	SnapshotRequestReason_value = map[string]int32{
		"SNAPSHOT_REQUEST_REASON_UNSPECIFIED":     0,
		"SNAPSHOT_REQUEST_REASON_STARTUP":         1,
		"SNAPSHOT_REQUEST_REASON_XRAY_RESTART":    2,
		"SNAPSHOT_REQUEST_REASON_REDELIVERY_GAP":  3,
		"SNAPSHOT_REQUEST_REASON_OPERATOR_FORCED": 4,
	}
)

func (x SnapshotRequestReason) Enum() *SnapshotRequestReason {
	p := new(SnapshotRequestReason)
	*p = x
	return p
}

func (x SnapshotRequestReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SnapshotRequestReason) Descriptor() protoreflect.EnumDescriptor {
	return file_vpn_agent_v1_agent_proto_enumTypes[5].Descriptor()
}

func (SnapshotRequestReason) Type() protoreflect.EnumType {
	return &file_vpn_agent_v1_agent_proto_enumTypes[5]
}

func (x SnapshotRequestReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SnapshotRequestReason.Descriptor instead.
func (SnapshotRequestReason) EnumDescriptor() ([]byte, []int) {
	return file_vpn_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

type SyncReportAckStatus int32

const (
	SyncReportAckStatus_SYNC_REPORT_ACK_STATUS_UNSPECIFIED SyncReportAckStatus = 0
	SyncReportAckStatus_SYNC_REPORT_ACK_STATUS_ACCEPTED    SyncReportAckStatus = 1
	SyncReportAckStatus_SYNC_REPORT_ACK_STATUS_SKIPPED     SyncReportAckStatus = 2
)

// Enum value maps for SyncReportAckStatus.
var (
	SyncReportAckStatus_name = map[int32]string{
		0: "SYNC_REPORT_ACK_STATUS_UNSPECIFIED",
		1: "SYNC_REPORT_ACK_STATUS_ACCEPTED",
		2: "SYNC_REPORT_ACK_STATUS_SKIPPED",
	}
	SyncReportAckStatus_value = map[string]int32{
		"SYNC_REPORT_ACK_STATUS_UNSPECIFIED": 0,
		"SYNC_REPORT_ACK_STATUS_ACCEPTED":    1,
		"SYNC_REPORT_ACK_STATUS_SKIPPED":     2,
	}
)

func (x SyncReportAckStatus) Enum() *SyncReportAckStatus {
	p := new(SyncReportAckStatus)
	*p = x
	return p
}

func (x SyncReportAckStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncReportAckStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_vpn_agent_v1_agent_proto_enumTypes[6].Descriptor()
}

func (SyncReportAckStatus) Type() protoreflect.EnumType {
	return &file_vpn_agent_v1_agent_proto_enumTypes[6]
}

func (x SyncReportAckStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncReportAckStatus.Descriptor instead.
func (SyncReportAckStatus) EnumDescriptor() ([]byte, []int) {
	return file_vpn_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

type AgentEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	EmittedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=emitted_at,json=emittedAt,proto3" json:"emitted_at,omitempty"`
	SnapshotId    *string                `protobuf:"bytes,4,opt,name=snapshot_id,json=snapshotId,proto3,oneof" json:"snapshot_id,omitempty"`
	Epoch         *uint64                `protobuf:"varint,5,opt,name=epoch,proto3,oneof" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEnvelope) Reset() {
	*x = AgentEnvelope{}
	mi := &file_vpn_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEnvelope) ProtoMessage() {}

func (x *AgentEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEnvelope.ProtoReflect.Descriptor instead.
func (*AgentEnvelope) Descriptor() ([]byte, []int) {
	return file_vpn_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentEnvelope) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *AgentEnvelope) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AgentEnvelope) GetEmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EmittedAt
	}
	return nil
}

func (x *AgentEnvelope) GetSnapshotId() string {
	if x != nil && x.SnapshotId != nil {
		return *x.SnapshotId
	}
	return ""
}

func (x *AgentEnvelope) GetEpoch() uint64 {
	if x != nil && x.Epoch != nil {
		return *x.Epoch
	}
	return 0
}

var File_vpn_agent_v1_agent_proto protoreflect.FileDescriptor

const file_vpn_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x18vpn/agent/v1/agent.proto\x12\fvpn.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe5\x01\n" +
	"\rAgentEnvelope\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x129\n" +
	"\n" +
	"emitted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\temittedAt\x12$\n" +
	"\vsnapshot_id\x18\x04 \x01(\tH\x00R\n" +
	"snapshotId\x88\x01\x01\x12\x19\n" +
	"\x05epoch\x18\x05 \x01(\x04H\x01R\x05epoch\x88\x01\x01B\x0e\n" +
	"\f_snapshot_idB\b\n" +
	"\x06_epoch*c\n" +
	"\fDesiredState\x12\x1d\n" +
	"\x19DESIRED_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14DESIRED_STATE_ACTIVE\x10\x01\x12\x1a\n" +
	"\x16DESIRED_STATE_INACTIVE\x10\x02*|\n" +
	"\fAppliedState\x12\x1d\n" +
	"\x19APPLIED_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15APPLIED_STATE_PENDING\x10\x01\x12\x19\n" +
	"\x15APPLIED_STATE_APPLIED\x10\x02\x12\x17\n" +
	"\x13APPLIED_STATE_ERROR\x10\x03*\xc3\x01\n" +
	"\fReportStatus\x12\x1d\n" +
	"\x19REPORT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15REPORT_STATUS_APPLIED\x10\x01\x12\x19\n" +
	"\x15REPORT_STATUS_PENDING\x10\x02\x12\x17\n" +
	"\x13REPORT_STATUS_ERROR\x10\x03\x12\x1f\n" +
	"\x1bREPORT_STATUS_SKIPPED_STALE\x10\x04\x12$\n" +
	" REPORT_STATUS_SKIPPED_IDEMPOTENT\x10\x05*8\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0ePROTOCOL_VLESS\x10\x01*\x94\x01\n" +
	"\rTransportKind\x12\x1e\n" +
	"\x1aTRANSPORT_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TRANSPORT_KIND_WS\x10\x01\x12\x18\n" +
	"\x14TRANSPORT_KIND_XHTTP\x10\x02\x12\x16\n" +
	"\x12TRANSPORT_KIND_TCP\x10\x03\x12\x1a\n" +
	"\x16TRANSPORT_KIND_REALITY\x10\x04*\xe8\x01\n" +
	"\x15SnapshotRequestReason\x12'\n" +
	"#SNAPSHOT_REQUEST_REASON_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fSNAPSHOT_REQUEST_REASON_STARTUP\x10\x01\x12(\n" +
	"$SNAPSHOT_REQUEST_REASON_XRAY_RESTART\x10\x02\x12*\n" +
	"&SNAPSHOT_REQUEST_REASON_REDELIVERY_GAP\x10\x03\x12+\n" +
	"'SNAPSHOT_REQUEST_REASON_OPERATOR_FORCED\x10\x04*\x86\x01\n" +
	"\x13SyncReportAckStatus\x12&\n" +
	"\"SYNC_REPORT_ACK_STATUS_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fSYNC_REPORT_ACK_STATUS_ACCEPTED\x10\x01\x12\"\n" +
	"\x1eSYNC_REPORT_ACK_STATUS_SKIPPED\x10\x02B\xb7\x01\n" +
	"\x10com.vpn.agent.v1B\n" +
	"AgentProtoP\x01ZEgithub.com/lannister-dev/go-node-agent/pkg/proto/vpn/agent/v1;agentv1\xa2\x02\x03VAX\xaa\x02\fVpn.Agent.V1\xca\x02\fVpn\\Agent\\V1\xe2\x02\x18Vpn\\Agent\\V1\\GPBMetadata\xea\x02\x0eVpn::Agent::V1b\x06proto3"

var (
	file_vpn_agent_v1_agent_proto_rawDescOnce sync.Once
	file_vpn_agent_v1_agent_proto_rawDescData []byte
)

func file_vpn_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_vpn_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_vpn_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vpn_agent_v1_agent_proto_rawDesc), len(file_vpn_agent_v1_agent_proto_rawDesc)))
	})
	return file_vpn_agent_v1_agent_proto_rawDescData
}

var file_vpn_agent_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_vpn_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_vpn_agent_v1_agent_proto_goTypes = []any{
	(DesiredState)(0),             // 0: vpn.agent.v1.DesiredState
	(AppliedState)(0),             // 1: vpn.agent.v1.AppliedState
	(ReportStatus)(0),             // 2: vpn.agent.v1.ReportStatus
	(Protocol)(0),                 // 3: vpn.agent.v1.Protocol
	(TransportKind)(0),            // 4: vpn.agent.v1.TransportKind
	(SnapshotRequestReason)(0),    // 5: vpn.agent.v1.SnapshotRequestReason
	(SyncReportAckStatus)(0),      // 6: vpn.agent.v1.SyncReportAckStatus
	(*AgentEnvelope)(nil),         // 7: vpn.agent.v1.AgentEnvelope
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_vpn_agent_v1_agent_proto_depIdxs = []int32{
	8, // 0: vpn.agent.v1.AgentEnvelope.emitted_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_vpn_agent_v1_agent_proto_init() }
func file_vpn_agent_v1_agent_proto_init() {
	if File_vpn_agent_v1_agent_proto != nil {
		return
	}
	file_vpn_agent_v1_agent_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vpn_agent_v1_agent_proto_rawDesc), len(file_vpn_agent_v1_agent_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vpn_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_vpn_agent_v1_agent_proto_depIdxs,
		EnumInfos:         file_vpn_agent_v1_agent_proto_enumTypes,
		MessageInfos:      file_vpn_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_vpn_agent_v1_agent_proto = out.File
	file_vpn_agent_v1_agent_proto_goTypes = nil
	file_vpn_agent_v1_agent_proto_depIdxs = nil
}
