// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: vpn/agent/v1/heartbeat.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeartbeatPoolHealth struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	SlotsTotal               uint32                 `protobuf:"varint,1,opt,name=slots_total,json=slotsTotal,proto3" json:"slots_total,omitempty"`
	SlotsActive              uint32                 `protobuf:"varint,2,opt,name=slots_active,json=slotsActive,proto3" json:"slots_active,omitempty"`
	DesiredBackends          uint32                 `protobuf:"varint,3,opt,name=desired_backends,json=desiredBackends,proto3" json:"desired_backends,omitempty"`
	DroppedOverflow          uint32                 `protobuf:"varint,4,opt,name=dropped_overflow,json=droppedOverflow,proto3" json:"dropped_overflow,omitempty"`
	LastApplyOk              bool                   `protobuf:"varint,5,opt,name=last_apply_ok,json=lastApplyOk,proto3" json:"last_apply_ok,omitempty"`
	LastApplyError           *string                `protobuf:"bytes,6,opt,name=last_apply_error,json=lastApplyError,proto3,oneof" json:"last_apply_error,omitempty"`
	ConsecutiveApplyFailures uint32                 `protobuf:"varint,7,opt,name=consecutive_apply_failures,json=consecutiveApplyFailures,proto3" json:"consecutive_apply_failures,omitempty"`
	LastAppliedGeneration    uint32                 `protobuf:"varint,8,opt,name=last_applied_generation,json=lastAppliedGeneration,proto3" json:"last_applied_generation,omitempty"`
	LastAppliedAt            *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_applied_at,json=lastAppliedAt,proto3,oneof" json:"last_applied_at,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *HeartbeatPoolHealth) Reset() {
	*x = HeartbeatPoolHealth{}
	mi := &file_vpn_agent_v1_heartbeat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPoolHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPoolHealth) ProtoMessage() {}

func (x *HeartbeatPoolHealth) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_agent_v1_heartbeat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPoolHealth.ProtoReflect.Descriptor instead.
func (*HeartbeatPoolHealth) Descriptor() ([]byte, []int) {
	return file_vpn_agent_v1_heartbeat_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatPoolHealth) GetSlotsTotal() uint32 {
	if x != nil {
		return x.SlotsTotal
	}
	return 0
}

func (x *HeartbeatPoolHealth) GetSlotsActive() uint32 {
	if x != nil {
		return x.SlotsActive
	}
	return 0
}

func (x *HeartbeatPoolHealth) GetDesiredBackends() uint32 {
	if x != nil {
		return x.DesiredBackends
	}
	return 0
}

func (x *HeartbeatPoolHealth) GetDroppedOverflow() uint32 {
	if x != nil {
		return x.DroppedOverflow
	}
	return 0
}

func (x *HeartbeatPoolHealth) GetLastApplyOk() bool {
	if x != nil {
		return x.LastApplyOk
	}
	return false
}

func (x *HeartbeatPoolHealth) GetLastApplyError() string {
	if x != nil && x.LastApplyError != nil {
		return *x.LastApplyError
	}
	return ""
}

func (x *HeartbeatPoolHealth) GetConsecutiveApplyFailures() uint32 {
	if x != nil {
		return x.ConsecutiveApplyFailures
	}
	return 0
}

func (x *HeartbeatPoolHealth) GetLastAppliedGeneration() uint32 {
	if x != nil {
		return x.LastAppliedGeneration
	}
	return 0
}

func (x *HeartbeatPoolHealth) GetLastAppliedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAppliedAt
	}
	return nil
}

type HeartbeatUpstreamHealth struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Configured               bool                   `protobuf:"varint,1,opt,name=configured,proto3" json:"configured,omitempty"`
	LastApplyOk              bool                   `protobuf:"varint,2,opt,name=last_apply_ok,json=lastApplyOk,proto3" json:"last_apply_ok,omitempty"`
	LastApplyError           *string                `protobuf:"bytes,3,opt,name=last_apply_error,json=lastApplyError,proto3,oneof" json:"last_apply_error,omitempty"`
	ConsecutiveApplyFailures uint32                 `protobuf:"varint,4,opt,name=consecutive_apply_failures,json=consecutiveApplyFailures,proto3" json:"consecutive_apply_failures,omitempty"`
	UpstreamNodeId           *string                `protobuf:"bytes,5,opt,name=upstream_node_id,json=upstreamNodeId,proto3,oneof" json:"upstream_node_id,omitempty"`
	UpstreamHost             *string                `protobuf:"bytes,6,opt,name=upstream_host,json=upstreamHost,proto3,oneof" json:"upstream_host,omitempty"`
	UpstreamAddr             *string                `protobuf:"bytes,7,opt,name=upstream_addr,json=upstreamAddr,proto3,oneof" json:"upstream_addr,omitempty"`
	LastAppliedAt            *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_applied_at,json=lastAppliedAt,proto3,oneof" json:"last_applied_at,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *HeartbeatUpstreamHealth) Reset() {
	*x = HeartbeatUpstreamHealth{}
	mi := &file_vpn_agent_v1_heartbeat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatUpstreamHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatUpstreamHealth) ProtoMessage() {}

func (x *HeartbeatUpstreamHealth) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_agent_v1_heartbeat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatUpstreamHealth.ProtoReflect.Descriptor instead.
func (*HeartbeatUpstreamHealth) Descriptor() ([]byte, []int) {
	return file_vpn_agent_v1_heartbeat_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatUpstreamHealth) GetConfigured() bool {
	if x != nil {
		return x.Configured
	}
	return false
}

func (x *HeartbeatUpstreamHealth) GetLastApplyOk() bool {
	if x != nil {
		return x.LastApplyOk
	}
	return false
}

func (x *HeartbeatUpstreamHealth) GetLastApplyError() string {
	if x != nil && x.LastApplyError != nil {
		return *x.LastApplyError
	}
	return ""
}

func (x *HeartbeatUpstreamHealth) GetConsecutiveApplyFailures() uint32 {
	if x != nil {
		return x.ConsecutiveApplyFailures
	}
	return 0
}

func (x *HeartbeatUpstreamHealth) GetUpstreamNodeId() string {
	if x != nil && x.UpstreamNodeId != nil {
		return *x.UpstreamNodeId
	}
	return ""
}

func (x *HeartbeatUpstreamHealth) GetUpstreamHost() string {
	if x != nil && x.UpstreamHost != nil {
		return *x.UpstreamHost
	}
	return ""
}

func (x *HeartbeatUpstreamHealth) GetUpstreamAddr() string {
	if x != nil && x.UpstreamAddr != nil {
		return *x.UpstreamAddr
	}
	return ""
}

func (x *HeartbeatUpstreamHealth) GetLastAppliedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAppliedAt
	}
	return nil
}

type HeartbeatEvent struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	SchemaVersion uint32                   `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	EventId       string                   `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	NodeId        string                   `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	EmittedAt     *timestamppb.Timestamp   `protobuf:"bytes,4,opt,name=emitted_at,json=emittedAt,proto3" json:"emitted_at,omitempty"`
	AgentVersion  string                   `protobuf:"bytes,5,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	IsHealthy     bool                     `protobuf:"varint,6,opt,name=is_healthy,json=isHealthy,proto3" json:"is_healthy,omitempty"`
	Ready         bool                     `protobuf:"varint,7,opt,name=ready,proto3" json:"ready,omitempty"`
	LastError     *string                  `protobuf:"bytes,8,opt,name=last_error,json=lastError,proto3,oneof" json:"last_error,omitempty"`
	PollCount     uint32                   `protobuf:"varint,9,opt,name=poll_count,json=pollCount,proto3" json:"poll_count,omitempty"`
	Applied       uint32                   `protobuf:"varint,10,opt,name=applied,proto3" json:"applied,omitempty"`
	Failed        uint32                   `protobuf:"varint,11,opt,name=failed,proto3" json:"failed,omitempty"`
	CpuPct        *float64                 `protobuf:"fixed64,12,opt,name=cpu_pct,json=cpuPct,proto3,oneof" json:"cpu_pct,omitempty"`
	MemPct        *float64                 `protobuf:"fixed64,13,opt,name=mem_pct,json=memPct,proto3,oneof" json:"mem_pct,omitempty"`
	BandwidthPct  *float64                 `protobuf:"fixed64,14,opt,name=bandwidth_pct,json=bandwidthPct,proto3,oneof" json:"bandwidth_pct,omitempty"`
	Pool          *HeartbeatPoolHealth     `protobuf:"bytes,15,opt,name=pool,proto3,oneof" json:"pool,omitempty"`
	Upstream      *HeartbeatUpstreamHealth `protobuf:"bytes,16,opt,name=upstream,proto3,oneof" json:"upstream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatEvent) Reset() {
	*x = HeartbeatEvent{}
	mi := &file_vpn_agent_v1_heartbeat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatEvent) ProtoMessage() {}

func (x *HeartbeatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_agent_v1_heartbeat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatEvent.ProtoReflect.Descriptor instead.
func (*HeartbeatEvent) Descriptor() ([]byte, []int) {
	return file_vpn_agent_v1_heartbeat_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatEvent) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *HeartbeatEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *HeartbeatEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatEvent) GetEmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EmittedAt
	}
	return nil
}

func (x *HeartbeatEvent) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *HeartbeatEvent) GetIsHealthy() bool {
	if x != nil {
		return x.IsHealthy
	}
	return false
}

func (x *HeartbeatEvent) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *HeartbeatEvent) GetLastError() string {
	if x != nil && x.LastError != nil {
		return *x.LastError
	}
	return ""
}

func (x *HeartbeatEvent) GetPollCount() uint32 {
	if x != nil {
		return x.PollCount
	}
	return 0
}

func (x *HeartbeatEvent) GetApplied() uint32 {
	if x != nil {
		return x.Applied
	}
	return 0
}

func (x *HeartbeatEvent) GetFailed() uint32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *HeartbeatEvent) GetCpuPct() float64 {
	if x != nil && x.CpuPct != nil {
		return *x.CpuPct
	}
	return 0
}

func (x *HeartbeatEvent) GetMemPct() float64 {
	if x != nil && x.MemPct != nil {
		return *x.MemPct
	}
	return 0
}

func (x *HeartbeatEvent) GetBandwidthPct() float64 {
	if x != nil && x.BandwidthPct != nil {
		return *x.BandwidthPct
	}
	return 0
}

func (x *HeartbeatEvent) GetPool() *HeartbeatPoolHealth {
	if x != nil {
		return x.Pool
	}
	return nil
}

func (x *HeartbeatEvent) GetUpstream() *HeartbeatUpstreamHealth {
	if x != nil {
		return x.Upstream
	}
	return nil
}

var File_vpn_agent_v1_heartbeat_proto protoreflect.FileDescriptor

const file_vpn_agent_v1_heartbeat_proto_rawDesc = "" +
	"\n" +
	"\x1cvpn/agent/v1/heartbeat.proto\x12\fvpn.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xea\x03\n" +
	"\x13HeartbeatPoolHealth\x12\x1f\n" +
	"\vslots_total\x18\x01 \x01(\rR\n" +
	"slotsTotal\x12!\n" +
	"\fslots_active\x18\x02 \x01(\rR\vslotsActive\x12)\n" +
	"\x10desired_backends\x18\x03 \x01(\rR\x0fdesiredBackends\x12)\n" +
	"\x10dropped_overflow\x18\x04 \x01(\rR\x0fdroppedOverflow\x12\"\n" +
	"\rlast_apply_ok\x18\x05 \x01(\bR\vlastApplyOk\x12-\n" +
	"\x10last_apply_error\x18\x06 \x01(\tH\x00R\x0elastApplyError\x88\x01\x01\x12<\n" +
	"\x1aconsecutive_apply_failures\x18\a \x01(\rR\x18consecutiveApplyFailures\x126\n" +
	"\x17last_applied_generation\x18\b \x01(\rR\x15lastAppliedGeneration\x12G\n" +
	"\x0flast_applied_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x01R\rlastAppliedAt\x88\x01\x01B\x13\n" +
	"\x11_last_apply_errorB\x12\n" +
	"\x10_last_applied_at\"\xf8\x03\n" +
	"\x17HeartbeatUpstreamHealth\x12\x1e\n" +
	"\n" +
	"configured\x18\x01 \x01(\bR\n" +
	"configured\x12\"\n" +
	"\rlast_apply_ok\x18\x02 \x01(\bR\vlastApplyOk\x12-\n" +
	"\x10last_apply_error\x18\x03 \x01(\tH\x00R\x0elastApplyError\x88\x01\x01\x12<\n" +
	"\x1aconsecutive_apply_failures\x18\x04 \x01(\rR\x18consecutiveApplyFailures\x12-\n" +
	"\x10upstream_node_id\x18\x05 \x01(\tH\x01R\x0eupstreamNodeId\x88\x01\x01\x12(\n" +
	"\rupstream_host\x18\x06 \x01(\tH\x02R\fupstreamHost\x88\x01\x01\x12(\n" +
	"\rupstream_addr\x18\a \x01(\tH\x03R\fupstreamAddr\x88\x01\x01\x12G\n" +
	"\x0flast_applied_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x04R\rlastAppliedAt\x88\x01\x01B\x13\n" +
	"\x11_last_apply_errorB\x13\n" +
	"\x11_upstream_node_idB\x10\n" +
	"\x0e_upstream_hostB\x10\n" +
	"\x0e_upstream_addrB\x12\n" +
	"\x10_last_applied_at\"\xae\x05\n" +
	"\x0eHeartbeatEvent\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x129\n" +
	"\n" +
	"emitted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\temittedAt\x12#\n" +
	"\ragent_version\x18\x05 \x01(\tR\fagentVersion\x12\x1d\n" +
	"\n" +
	"is_healthy\x18\x06 \x01(\bR\tisHealthy\x12\x14\n" +
	"\x05ready\x18\a \x01(\bR\x05ready\x12\"\n" +
	"\n" +
	"last_error\x18\b \x01(\tH\x00R\tlastError\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"poll_count\x18\t \x01(\rR\tpollCount\x12\x18\n" +
	"\aapplied\x18\n" +
	" \x01(\rR\aapplied\x12\x16\n" +
	"\x06failed\x18\v \x01(\rR\x06failed\x12\x1c\n" +
	"\acpu_pct\x18\f \x01(\x01H\x01R\x06cpuPct\x88\x01\x01\x12\x1c\n" +
	"\amem_pct\x18\r \x01(\x01H\x02R\x06memPct\x88\x01\x01\x12(\n" +
	"\rbandwidth_pct\x18\x0e \x01(\x01H\x03R\fbandwidthPct\x88\x01\x01\x12:\n" +
	"\x04pool\x18\x0f \x01(\v2!.vpn.agent.v1.HeartbeatPoolHealthH\x04R\x04pool\x88\x01\x01\x12F\n" +
	"\bupstream\x18\x10 \x01(\v2%.vpn.agent.v1.HeartbeatUpstreamHealthH\x05R\bupstream\x88\x01\x01B\r\n" +
	"\v_last_errorB\n" +
	"\n" +
	"\b_cpu_pctB\n" +
	"\n" +
	"\b_mem_pctB\x10\n" +
	"\x0e_bandwidth_pctB\a\n" +
	"\x05_poolB\v\n" +
	"\t_upstreamB\xbb\x01\n" +
	"\x10com.vpn.agent.v1B\x0eHeartbeatProtoP\x01ZEgithub.com/lannister-dev/go-node-agent/pkg/proto/vpn/agent/v1;agentv1\xa2\x02\x03VAX\xaa\x02\fVpn.Agent.V1\xca\x02\fVpn\\Agent\\V1\xe2\x02\x18Vpn\\Agent\\V1\\GPBMetadata\xea\x02\x0eVpn::Agent::V1b\x06proto3"

var (
	file_vpn_agent_v1_heartbeat_proto_rawDescOnce sync.Once
	file_vpn_agent_v1_heartbeat_proto_rawDescData []byte
)

func file_vpn_agent_v1_heartbeat_proto_rawDescGZIP() []byte {
	file_vpn_agent_v1_heartbeat_proto_rawDescOnce.Do(func() {
		file_vpn_agent_v1_heartbeat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vpn_agent_v1_heartbeat_proto_rawDesc), len(file_vpn_agent_v1_heartbeat_proto_rawDesc)))
	})
	return file_vpn_agent_v1_heartbeat_proto_rawDescData
}

var file_vpn_agent_v1_heartbeat_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_vpn_agent_v1_heartbeat_proto_goTypes = []any{
	(*HeartbeatPoolHealth)(nil),     // 0: vpn.agent.v1.HeartbeatPoolHealth
	(*HeartbeatUpstreamHealth)(nil), // 1: vpn.agent.v1.HeartbeatUpstreamHealth
	(*HeartbeatEvent)(nil),          // 2: vpn.agent.v1.HeartbeatEvent
	(*timestamppb.Timestamp)(nil),   // 3: google.protobuf.Timestamp
}
var file_vpn_agent_v1_heartbeat_proto_depIdxs = []int32{
	3, // 0: vpn.agent.v1.HeartbeatPoolHealth.last_applied_at:type_name -> google.protobuf.Timestamp
	3, // 1: vpn.agent.v1.HeartbeatUpstreamHealth.last_applied_at:type_name -> google.protobuf.Timestamp
	3, // 2: vpn.agent.v1.HeartbeatEvent.emitted_at:type_name -> google.protobuf.Timestamp
	0, // 3: vpn.agent.v1.HeartbeatEvent.pool:type_name -> vpn.agent.v1.HeartbeatPoolHealth
	1, // 4: vpn.agent.v1.HeartbeatEvent.upstream:type_name -> vpn.agent.v1.HeartbeatUpstreamHealth
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_vpn_agent_v1_heartbeat_proto_init() }
func file_vpn_agent_v1_heartbeat_proto_init() {
	if File_vpn_agent_v1_heartbeat_proto != nil {
		return
	}
	file_vpn_agent_v1_heartbeat_proto_msgTypes[0].OneofWrappers = []any{}
	file_vpn_agent_v1_heartbeat_proto_msgTypes[1].OneofWrappers = []any{}
	file_vpn_agent_v1_heartbeat_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vpn_agent_v1_heartbeat_proto_rawDesc), len(file_vpn_agent_v1_heartbeat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vpn_agent_v1_heartbeat_proto_goTypes,
		DependencyIndexes: file_vpn_agent_v1_heartbeat_proto_depIdxs,
		MessageInfos:      file_vpn_agent_v1_heartbeat_proto_msgTypes,
	}.Build()
	File_vpn_agent_v1_heartbeat_proto = out.File
	file_vpn_agent_v1_heartbeat_proto_goTypes = nil
	file_vpn_agent_v1_heartbeat_proto_depIdxs = nil
}
