// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: vpn/agent/v1/placement.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlacementCommandEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Envelope         *AgentEnvelope         `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	EventId          string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	PlacementId      string                 `protobuf:"bytes,3,opt,name=placement_id,json=placementId,proto3" json:"placement_id,omitempty"`
	KeyId            string                 `protobuf:"bytes,4,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	OpVersion        uint64                 `protobuf:"varint,5,opt,name=op_version,json=opVersion,proto3" json:"op_version,omitempty"`
	DesiredState     DesiredState           `protobuf:"varint,6,opt,name=desired_state,json=desiredState,proto3,enum=vpn.agent.v1.DesiredState" json:"desired_state,omitempty"`
	BackendNodeId    string                 `protobuf:"bytes,7,opt,name=backend_node_id,json=backendNodeId,proto3" json:"backend_node_id,omitempty"`
	Protocol         Protocol               `protobuf:"varint,8,opt,name=protocol,proto3,enum=vpn.agent.v1.Protocol" json:"protocol,omitempty"`
	Transport        TransportKind          `protobuf:"varint,9,opt,name=transport,proto3,enum=vpn.agent.v1.TransportKind" json:"transport,omitempty"`
	ClientId         string                 `protobuf:"bytes,10,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	IsRevoked        bool                   `protobuf:"varint,11,opt,name=is_revoked,json=isRevoked,proto3" json:"is_revoked,omitempty"`
	SnapshotComplete bool                   `protobuf:"varint,12,opt,name=snapshot_complete,json=snapshotComplete,proto3" json:"snapshot_complete,omitempty"`
	ValidUntil       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=valid_until,json=validUntil,proto3,oneof" json:"valid_until,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PlacementCommandEvent) Reset() {
	*x = PlacementCommandEvent{}
	mi := &file_vpn_agent_v1_placement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlacementCommandEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlacementCommandEvent) ProtoMessage() {}

func (x *PlacementCommandEvent) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_agent_v1_placement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlacementCommandEvent.ProtoReflect.Descriptor instead.
func (*PlacementCommandEvent) Descriptor() ([]byte, []int) {
	return file_vpn_agent_v1_placement_proto_rawDescGZIP(), []int{0}
}

func (x *PlacementCommandEvent) GetEnvelope() *AgentEnvelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *PlacementCommandEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *PlacementCommandEvent) GetPlacementId() string {
	if x != nil {
		return x.PlacementId
	}
	return ""
}

func (x *PlacementCommandEvent) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *PlacementCommandEvent) GetOpVersion() uint64 {
	if x != nil {
		return x.OpVersion
	}
	return 0
}

func (x *PlacementCommandEvent) GetDesiredState() DesiredState {
	if x != nil {
		return x.DesiredState
	}
	return DesiredState_DESIRED_STATE_UNSPECIFIED
}

func (x *PlacementCommandEvent) GetBackendNodeId() string {
	if x != nil {
		return x.BackendNodeId
	}
	return ""
}

func (x *PlacementCommandEvent) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *PlacementCommandEvent) GetTransport() TransportKind {
	if x != nil {
		return x.Transport
	}
	return TransportKind_TRANSPORT_KIND_UNSPECIFIED
}

func (x *PlacementCommandEvent) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *PlacementCommandEvent) GetIsRevoked() bool {
	if x != nil {
		return x.IsRevoked
	}
	return false
}

func (x *PlacementCommandEvent) GetSnapshotComplete() bool {
	if x != nil {
		return x.SnapshotComplete
	}
	return false
}

func (x *PlacementCommandEvent) GetValidUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidUntil
	}
	return nil
}

func (x *PlacementCommandEvent) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type PlacementApplyResultEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Envelope       *AgentEnvelope         `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	EventId        string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	PlacementId    string                 `protobuf:"bytes,3,opt,name=placement_id,json=placementId,proto3" json:"placement_id,omitempty"`
	OpVersion      uint64                 `protobuf:"varint,4,opt,name=op_version,json=opVersion,proto3" json:"op_version,omitempty"`
	AppliedState   AppliedState           `protobuf:"varint,5,opt,name=applied_state,json=appliedState,proto3,enum=vpn.agent.v1.AppliedState" json:"applied_state,omitempty"`
	ReportStatus   *ReportStatus          `protobuf:"varint,6,opt,name=report_status,json=reportStatus,proto3,enum=vpn.agent.v1.ReportStatus,oneof" json:"report_status,omitempty"`
	Retryable      bool                   `protobuf:"varint,7,opt,name=retryable,proto3" json:"retryable,omitempty"`
	Error          *string                `protobuf:"bytes,8,opt,name=error,proto3,oneof" json:"error,omitempty"`
	InventoryHash  *string                `protobuf:"bytes,9,opt,name=inventory_hash,json=inventoryHash,proto3,oneof" json:"inventory_hash,omitempty"`
	InventoryCount *uint64                `protobuf:"varint,10,opt,name=inventory_count,json=inventoryCount,proto3,oneof" json:"inventory_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlacementApplyResultEvent) Reset() {
	*x = PlacementApplyResultEvent{}
	mi := &file_vpn_agent_v1_placement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlacementApplyResultEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlacementApplyResultEvent) ProtoMessage() {}

func (x *PlacementApplyResultEvent) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_agent_v1_placement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlacementApplyResultEvent.ProtoReflect.Descriptor instead.
func (*PlacementApplyResultEvent) Descriptor() ([]byte, []int) {
	return file_vpn_agent_v1_placement_proto_rawDescGZIP(), []int{1}
}

func (x *PlacementApplyResultEvent) GetEnvelope() *AgentEnvelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *PlacementApplyResultEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *PlacementApplyResultEvent) GetPlacementId() string {
	if x != nil {
		return x.PlacementId
	}
	return ""
}

func (x *PlacementApplyResultEvent) GetOpVersion() uint64 {
	if x != nil {
		return x.OpVersion
	}
	return 0
}

func (x *PlacementApplyResultEvent) GetAppliedState() AppliedState {
	if x != nil {
		return x.AppliedState
	}
	return AppliedState_APPLIED_STATE_UNSPECIFIED
}

func (x *PlacementApplyResultEvent) GetReportStatus() ReportStatus {
	if x != nil && x.ReportStatus != nil {
		return *x.ReportStatus
	}
	return ReportStatus_REPORT_STATUS_UNSPECIFIED
}

func (x *PlacementApplyResultEvent) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *PlacementApplyResultEvent) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *PlacementApplyResultEvent) GetInventoryHash() string {
	if x != nil && x.InventoryHash != nil {
		return *x.InventoryHash
	}
	return ""
}

func (x *PlacementApplyResultEvent) GetInventoryCount() uint64 {
	if x != nil && x.InventoryCount != nil {
		return *x.InventoryCount
	}
	return 0
}

type PlacementApplyAckEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *AgentEnvelope         `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	PlacementId   string                 `protobuf:"bytes,3,opt,name=placement_id,json=placementId,proto3" json:"placement_id,omitempty"`
	OpVersion     uint64                 `protobuf:"varint,4,opt,name=op_version,json=opVersion,proto3" json:"op_version,omitempty"`
	Status        ReportStatus           `protobuf:"varint,5,opt,name=status,proto3,enum=vpn.agent.v1.ReportStatus" json:"status,omitempty"`
	Error         *string                `protobuf:"bytes,6,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlacementApplyAckEvent) Reset() {
	*x = PlacementApplyAckEvent{}
	mi := &file_vpn_agent_v1_placement_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlacementApplyAckEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlacementApplyAckEvent) ProtoMessage() {}

func (x *PlacementApplyAckEvent) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_agent_v1_placement_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlacementApplyAckEvent.ProtoReflect.Descriptor instead.
func (*PlacementApplyAckEvent) Descriptor() ([]byte, []int) {
	return file_vpn_agent_v1_placement_proto_rawDescGZIP(), []int{2}
}

func (x *PlacementApplyAckEvent) GetEnvelope() *AgentEnvelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *PlacementApplyAckEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *PlacementApplyAckEvent) GetPlacementId() string {
	if x != nil {
		return x.PlacementId
	}
	return ""
}

func (x *PlacementApplyAckEvent) GetOpVersion() uint64 {
	if x != nil {
		return x.OpVersion
	}
	return 0
}

func (x *PlacementApplyAckEvent) GetStatus() ReportStatus {
	if x != nil {
		return x.Status
	}
	return ReportStatus_REPORT_STATUS_UNSPECIFIED
}

func (x *PlacementApplyAckEvent) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_vpn_agent_v1_placement_proto protoreflect.FileDescriptor

const file_vpn_agent_v1_placement_proto_rawDesc = "" +
	"\n" +
	"\x1cvpn/agent/v1/placement.proto\x12\fvpn.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18vpn/agent/v1/agent.proto\"\xa6\x05\n" +
	"\x15PlacementCommandEvent\x127\n" +
	"\benvelope\x18\x01 \x01(\v2\x1b.vpn.agent.v1.AgentEnvelopeR\benvelope\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12!\n" +
	"\fplacement_id\x18\x03 \x01(\tR\vplacementId\x12\x15\n" +
	"\x06key_id\x18\x04 \x01(\tR\x05keyId\x12\x1d\n" +
	"\n" +
	"op_version\x18\x05 \x01(\x04R\topVersion\x12?\n" +
	"\rdesired_state\x18\x06 \x01(\x0e2\x1a.vpn.agent.v1.DesiredStateR\fdesiredState\x12&\n" +
	"\x0fbackend_node_id\x18\a \x01(\tR\rbackendNodeId\x122\n" +
	"\bprotocol\x18\b \x01(\x0e2\x16.vpn.agent.v1.ProtocolR\bprotocol\x129\n" +
	"\ttransport\x18\t \x01(\x0e2\x1b.vpn.agent.v1.TransportKindR\ttransport\x12\x1b\n" +
	"\tclient_id\x18\n" +
	" \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"is_revoked\x18\v \x01(\bR\tisRevoked\x12+\n" +
	"\x11snapshot_complete\x18\f \x01(\bR\x10snapshotComplete\x12@\n" +
	"\vvalid_until\x18\r \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"validUntil\x88\x01\x01\x12>\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampH\x01R\tupdatedAt\x88\x01\x01B\x0e\n" +
	"\f_valid_untilB\r\n" +
	"\v_updated_at\"\x8e\x04\n" +
	"\x19PlacementApplyResultEvent\x127\n" +
	"\benvelope\x18\x01 \x01(\v2\x1b.vpn.agent.v1.AgentEnvelopeR\benvelope\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12!\n" +
	"\fplacement_id\x18\x03 \x01(\tR\vplacementId\x12\x1d\n" +
	"\n" +
	"op_version\x18\x04 \x01(\x04R\topVersion\x12?\n" +
	"\rapplied_state\x18\x05 \x01(\x0e2\x1a.vpn.agent.v1.AppliedStateR\fappliedState\x12D\n" +
	"\rreport_status\x18\x06 \x01(\x0e2\x1a.vpn.agent.v1.ReportStatusH\x00R\freportStatus\x88\x01\x01\x12\x1c\n" +
	"\tretryable\x18\a \x01(\bR\tretryable\x12\x19\n" +
	"\x05error\x18\b \x01(\tH\x01R\x05error\x88\x01\x01\x12*\n" +
	"\x0einventory_hash\x18\t \x01(\tH\x02R\rinventoryHash\x88\x01\x01\x12,\n" +
	"\x0finventory_count\x18\n" +
	" \x01(\x04H\x03R\x0einventoryCount\x88\x01\x01B\x10\n" +
	"\x0e_report_statusB\b\n" +
	"\x06_errorB\x11\n" +
	"\x0f_inventory_hashB\x12\n" +
	"\x10_inventory_count\"\x87\x02\n" +
	"\x16PlacementApplyAckEvent\x127\n" +
	"\benvelope\x18\x01 \x01(\v2\x1b.vpn.agent.v1.AgentEnvelopeR\benvelope\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12!\n" +
	"\fplacement_id\x18\x03 \x01(\tR\vplacementId\x12\x1d\n" +
	"\n" +
	"op_version\x18\x04 \x01(\x04R\topVersion\x122\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1a.vpn.agent.v1.ReportStatusR\x06status\x12\x19\n" +
	"\x05error\x18\x06 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_errorB\xbb\x01\n" +
	"\x10com.vpn.agent.v1B\x0ePlacementProtoP\x01ZEgithub.com/lannister-dev/go-node-agent/pkg/proto/vpn/agent/v1;agentv1\xa2\x02\x03VAX\xaa\x02\fVpn.Agent.V1\xca\x02\fVpn\\Agent\\V1\xe2\x02\x18Vpn\\Agent\\V1\\GPBMetadata\xea\x02\x0eVpn::Agent::V1b\x06proto3"

var (
	file_vpn_agent_v1_placement_proto_rawDescOnce sync.Once
	file_vpn_agent_v1_placement_proto_rawDescData []byte
)

func file_vpn_agent_v1_placement_proto_rawDescGZIP() []byte {
	file_vpn_agent_v1_placement_proto_rawDescOnce.Do(func() {
		file_vpn_agent_v1_placement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vpn_agent_v1_placement_proto_rawDesc), len(file_vpn_agent_v1_placement_proto_rawDesc)))
	})
	return file_vpn_agent_v1_placement_proto_rawDescData
}

var file_vpn_agent_v1_placement_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_vpn_agent_v1_placement_proto_goTypes = []any{
	(*PlacementCommandEvent)(nil),     // 0: vpn.agent.v1.PlacementCommandEvent
	(*PlacementApplyResultEvent)(nil), // 1: vpn.agent.v1.PlacementApplyResultEvent
	(*PlacementApplyAckEvent)(nil),    // 2: vpn.agent.v1.PlacementApplyAckEvent
	(*AgentEnvelope)(nil),             // 3: vpn.agent.v1.AgentEnvelope
	(DesiredState)(0),                 // 4: vpn.agent.v1.DesiredState
	(Protocol)(0),                     // 5: vpn.agent.v1.Protocol
	(TransportKind)(0),                // 6: vpn.agent.v1.TransportKind
	(*timestamppb.Timestamp)(nil),     // 7: google.protobuf.Timestamp
	(AppliedState)(0),                 // 8: vpn.agent.v1.AppliedState
	(ReportStatus)(0),                 // 9: vpn.agent.v1.ReportStatus
}
var file_vpn_agent_v1_placement_proto_depIdxs = []int32{
	3,  // 0: vpn.agent.v1.PlacementCommandEvent.envelope:type_name -> vpn.agent.v1.AgentEnvelope
	4,  // 1: vpn.agent.v1.PlacementCommandEvent.desired_state:type_name -> vpn.agent.v1.DesiredState
	5,  // 2: vpn.agent.v1.PlacementCommandEvent.protocol:type_name -> vpn.agent.v1.Protocol
	6,  // 3: vpn.agent.v1.PlacementCommandEvent.transport:type_name -> vpn.agent.v1.TransportKind
	7,  // 4: vpn.agent.v1.PlacementCommandEvent.valid_until:type_name -> google.protobuf.Timestamp
	7,  // 5: vpn.agent.v1.PlacementCommandEvent.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 6: vpn.agent.v1.PlacementApplyResultEvent.envelope:type_name -> vpn.agent.v1.AgentEnvelope
	8,  // 7: vpn.agent.v1.PlacementApplyResultEvent.applied_state:type_name -> vpn.agent.v1.AppliedState
	9,  // 8: vpn.agent.v1.PlacementApplyResultEvent.report_status:type_name -> vpn.agent.v1.ReportStatus
	3,  // 9: vpn.agent.v1.PlacementApplyAckEvent.envelope:type_name -> vpn.agent.v1.AgentEnvelope
	9,  // 10: vpn.agent.v1.PlacementApplyAckEvent.status:type_name -> vpn.agent.v1.ReportStatus
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_vpn_agent_v1_placement_proto_init() }
func file_vpn_agent_v1_placement_proto_init() {
	if File_vpn_agent_v1_placement_proto != nil {
		return
	}
	file_vpn_agent_v1_agent_proto_init()
	file_vpn_agent_v1_placement_proto_msgTypes[0].OneofWrappers = []any{}
	file_vpn_agent_v1_placement_proto_msgTypes[1].OneofWrappers = []any{}
	file_vpn_agent_v1_placement_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vpn_agent_v1_placement_proto_rawDesc), len(file_vpn_agent_v1_placement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vpn_agent_v1_placement_proto_goTypes,
		DependencyIndexes: file_vpn_agent_v1_placement_proto_depIdxs,
		MessageInfos:      file_vpn_agent_v1_placement_proto_msgTypes,
	}.Build()
	File_vpn_agent_v1_placement_proto = out.File
	file_vpn_agent_v1_placement_proto_goTypes = nil
	file_vpn_agent_v1_placement_proto_depIdxs = nil
}
