// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: vpn/agent/v1/snapshot.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SnapshotRequestEvent struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion        uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	NodeId               string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	RequestedAt          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	Reason               SnapshotRequestReason  `protobuf:"varint,4,opt,name=reason,proto3,enum=vpn.agent.v1.SnapshotRequestReason" json:"reason,omitempty"`
	KnownSnapshotId      *string                `protobuf:"bytes,5,opt,name=known_snapshot_id,json=knownSnapshotId,proto3,oneof" json:"known_snapshot_id,omitempty"`
	LastCommandStreamSeq *uint64                `protobuf:"varint,6,opt,name=last_command_stream_seq,json=lastCommandStreamSeq,proto3,oneof" json:"last_command_stream_seq,omitempty"`
	LastSeenXrayUptime   *uint64                `protobuf:"varint,7,opt,name=last_seen_xray_uptime,json=lastSeenXrayUptime,proto3,oneof" json:"last_seen_xray_uptime,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SnapshotRequestEvent) Reset() {
	*x = SnapshotRequestEvent{}
	mi := &file_vpn_agent_v1_snapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequestEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequestEvent) ProtoMessage() {}

func (x *SnapshotRequestEvent) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_agent_v1_snapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequestEvent.ProtoReflect.Descriptor instead.
func (*SnapshotRequestEvent) Descriptor() ([]byte, []int) {
	return file_vpn_agent_v1_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *SnapshotRequestEvent) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *SnapshotRequestEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SnapshotRequestEvent) GetRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestedAt
	}
	return nil
}

func (x *SnapshotRequestEvent) GetReason() SnapshotRequestReason {
	if x != nil {
		return x.Reason
	}
	return SnapshotRequestReason_SNAPSHOT_REQUEST_REASON_UNSPECIFIED
}

func (x *SnapshotRequestEvent) GetKnownSnapshotId() string {
	if x != nil && x.KnownSnapshotId != nil {
		return *x.KnownSnapshotId
	}
	return ""
}

func (x *SnapshotRequestEvent) GetLastCommandStreamSeq() uint64 {
	if x != nil && x.LastCommandStreamSeq != nil {
		return *x.LastCommandStreamSeq
	}
	return 0
}

func (x *SnapshotRequestEvent) GetLastSeenXrayUptime() uint64 {
	if x != nil && x.LastSeenXrayUptime != nil {
		return *x.LastSeenXrayUptime
	}
	return 0
}

type SnapshotChunkEvent struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Envelope      *AgentEnvelope           `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	ChunkIndex    uint32                   `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	IsLastChunk   bool                     `protobuf:"varint,3,opt,name=is_last_chunk,json=isLastChunk,proto3" json:"is_last_chunk,omitempty"`
	Items         []*PlacementCommandEvent `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotChunkEvent) Reset() {
	*x = SnapshotChunkEvent{}
	mi := &file_vpn_agent_v1_snapshot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotChunkEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotChunkEvent) ProtoMessage() {}

func (x *SnapshotChunkEvent) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_agent_v1_snapshot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotChunkEvent.ProtoReflect.Descriptor instead.
func (*SnapshotChunkEvent) Descriptor() ([]byte, []int) {
	return file_vpn_agent_v1_snapshot_proto_rawDescGZIP(), []int{1}
}

func (x *SnapshotChunkEvent) GetEnvelope() *AgentEnvelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *SnapshotChunkEvent) GetChunkIndex() uint32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *SnapshotChunkEvent) GetIsLastChunk() bool {
	if x != nil {
		return x.IsLastChunk
	}
	return false
}

func (x *SnapshotChunkEvent) GetItems() []*PlacementCommandEvent {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_vpn_agent_v1_snapshot_proto protoreflect.FileDescriptor

const file_vpn_agent_v1_snapshot_proto_rawDesc = "" +
	"\n" +
	"\x1bvpn/agent/v1/snapshot.proto\x12\fvpn.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18vpn/agent/v1/agent.proto\x1a\x1cvpn/agent/v1/placement.proto\"\xc3\x03\n" +
	"\x14SnapshotRequestEvent\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12=\n" +
	"\frequested_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vrequestedAt\x12;\n" +
	"\x06reason\x18\x04 \x01(\x0e2#.vpn.agent.v1.SnapshotRequestReasonR\x06reason\x12/\n" +
	"\x11known_snapshot_id\x18\x05 \x01(\tH\x00R\x0fknownSnapshotId\x88\x01\x01\x12:\n" +
	"\x17last_command_stream_seq\x18\x06 \x01(\x04H\x01R\x14lastCommandStreamSeq\x88\x01\x01\x126\n" +
	"\x15last_seen_xray_uptime\x18\a \x01(\x04H\x02R\x12lastSeenXrayUptime\x88\x01\x01B\x14\n" +
	"\x12_known_snapshot_idB\x1a\n" +
	"\x18_last_command_stream_seqB\x18\n" +
	"\x16_last_seen_xray_uptime\"\xcd\x01\n" +
	"\x12SnapshotChunkEvent\x127\n" +
	"\benvelope\x18\x01 \x01(\v2\x1b.vpn.agent.v1.AgentEnvelopeR\benvelope\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\rR\n" +
	"chunkIndex\x12\"\n" +
	"\ris_last_chunk\x18\x03 \x01(\bR\visLastChunk\x129\n" +
	"\x05items\x18\x04 \x03(\v2#.vpn.agent.v1.PlacementCommandEventR\x05itemsB\xba\x01\n" +
	"\x10com.vpn.agent.v1B\rSnapshotProtoP\x01ZEgithub.com/lannister-dev/go-node-agent/pkg/proto/vpn/agent/v1;agentv1\xa2\x02\x03VAX\xaa\x02\fVpn.Agent.V1\xca\x02\fVpn\\Agent\\V1\xe2\x02\x18Vpn\\Agent\\V1\\GPBMetadata\xea\x02\x0eVpn::Agent::V1b\x06proto3"

var (
	file_vpn_agent_v1_snapshot_proto_rawDescOnce sync.Once
	file_vpn_agent_v1_snapshot_proto_rawDescData []byte
)

func file_vpn_agent_v1_snapshot_proto_rawDescGZIP() []byte {
	file_vpn_agent_v1_snapshot_proto_rawDescOnce.Do(func() {
		file_vpn_agent_v1_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vpn_agent_v1_snapshot_proto_rawDesc), len(file_vpn_agent_v1_snapshot_proto_rawDesc)))
	})
	return file_vpn_agent_v1_snapshot_proto_rawDescData
}

var file_vpn_agent_v1_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vpn_agent_v1_snapshot_proto_goTypes = []any{
	(*SnapshotRequestEvent)(nil),  // 0: vpn.agent.v1.SnapshotRequestEvent
	(*SnapshotChunkEvent)(nil),    // 1: vpn.agent.v1.SnapshotChunkEvent
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(SnapshotRequestReason)(0),    // 3: vpn.agent.v1.SnapshotRequestReason
	(*AgentEnvelope)(nil),         // 4: vpn.agent.v1.AgentEnvelope
	(*PlacementCommandEvent)(nil), // 5: vpn.agent.v1.PlacementCommandEvent
}
var file_vpn_agent_v1_snapshot_proto_depIdxs = []int32{
	2, // 0: vpn.agent.v1.SnapshotRequestEvent.requested_at:type_name -> google.protobuf.Timestamp
	3, // 1: vpn.agent.v1.SnapshotRequestEvent.reason:type_name -> vpn.agent.v1.SnapshotRequestReason
	4, // 2: vpn.agent.v1.SnapshotChunkEvent.envelope:type_name -> vpn.agent.v1.AgentEnvelope
	5, // 3: vpn.agent.v1.SnapshotChunkEvent.items:type_name -> vpn.agent.v1.PlacementCommandEvent
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_vpn_agent_v1_snapshot_proto_init() }
func file_vpn_agent_v1_snapshot_proto_init() {
	if File_vpn_agent_v1_snapshot_proto != nil {
		return
	}
	file_vpn_agent_v1_agent_proto_init()
	file_vpn_agent_v1_placement_proto_init()
	file_vpn_agent_v1_snapshot_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vpn_agent_v1_snapshot_proto_rawDesc), len(file_vpn_agent_v1_snapshot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vpn_agent_v1_snapshot_proto_goTypes,
		DependencyIndexes: file_vpn_agent_v1_snapshot_proto_depIdxs,
		MessageInfos:      file_vpn_agent_v1_snapshot_proto_msgTypes,
	}.Build()
	File_vpn_agent_v1_snapshot_proto = out.File
	file_vpn_agent_v1_snapshot_proto_goTypes = nil
	file_vpn_agent_v1_snapshot_proto_depIdxs = nil
}
