// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: vpn/agent/v1/stored.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoredPlacement struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	KeyId            string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	ClientId         string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	NodeId           string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	BackendNodeId    string                 `protobuf:"bytes,5,opt,name=backend_node_id,json=backendNodeId,proto3" json:"backend_node_id,omitempty"`
	OpVersion        uint64                 `protobuf:"varint,6,opt,name=op_version,json=opVersion,proto3" json:"op_version,omitempty"`
	DesiredState     DesiredState           `protobuf:"varint,7,opt,name=desired_state,json=desiredState,proto3,enum=vpn.agent.v1.DesiredState" json:"desired_state,omitempty"`
	AppliedState     AppliedState           `protobuf:"varint,8,opt,name=applied_state,json=appliedState,proto3,enum=vpn.agent.v1.AppliedState" json:"applied_state,omitempty"`
	Transport        TransportKind          `protobuf:"varint,9,opt,name=transport,proto3,enum=vpn.agent.v1.TransportKind" json:"transport,omitempty"`
	Protocol         Protocol               `protobuf:"varint,10,opt,name=protocol,proto3,enum=vpn.agent.v1.Protocol" json:"protocol,omitempty"`
	IsRevoked        bool                   `protobuf:"varint,11,opt,name=is_revoked,json=isRevoked,proto3" json:"is_revoked,omitempty"`
	ValidUntil       *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=valid_until,json=validUntil,proto3,oneof" json:"valid_until,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at,omitempty"`
	LastAppliedAt    *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=last_applied_at,json=lastAppliedAt,proto3,oneof" json:"last_applied_at,omitempty"`
	EntryOverrideTag string                 `protobuf:"bytes,15,opt,name=entry_override_tag,json=entryOverrideTag,proto3" json:"entry_override_tag,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StoredPlacement) Reset() {
	*x = StoredPlacement{}
	mi := &file_vpn_agent_v1_stored_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredPlacement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredPlacement) ProtoMessage() {}

func (x *StoredPlacement) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_agent_v1_stored_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredPlacement.ProtoReflect.Descriptor instead.
func (*StoredPlacement) Descriptor() ([]byte, []int) {
	return file_vpn_agent_v1_stored_proto_rawDescGZIP(), []int{0}
}

func (x *StoredPlacement) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StoredPlacement) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *StoredPlacement) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *StoredPlacement) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StoredPlacement) GetBackendNodeId() string {
	if x != nil {
		return x.BackendNodeId
	}
	return ""
}

func (x *StoredPlacement) GetOpVersion() uint64 {
	if x != nil {
		return x.OpVersion
	}
	return 0
}

func (x *StoredPlacement) GetDesiredState() DesiredState {
	if x != nil {
		return x.DesiredState
	}
	return DesiredState_DESIRED_STATE_UNSPECIFIED
}

func (x *StoredPlacement) GetAppliedState() AppliedState {
	if x != nil {
		return x.AppliedState
	}
	return AppliedState_APPLIED_STATE_UNSPECIFIED
}

func (x *StoredPlacement) GetTransport() TransportKind {
	if x != nil {
		return x.Transport
	}
	return TransportKind_TRANSPORT_KIND_UNSPECIFIED
}

func (x *StoredPlacement) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *StoredPlacement) GetIsRevoked() bool {
	if x != nil {
		return x.IsRevoked
	}
	return false
}

func (x *StoredPlacement) GetValidUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidUntil
	}
	return nil
}

func (x *StoredPlacement) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *StoredPlacement) GetLastAppliedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAppliedAt
	}
	return nil
}

func (x *StoredPlacement) GetEntryOverrideTag() string {
	if x != nil {
		return x.EntryOverrideTag
	}
	return ""
}

type StoredIdentity struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AgentInstanceId string                 `protobuf:"bytes,2,opt,name=agent_instance_id,json=agentInstanceId,proto3" json:"agent_instance_id,omitempty"`
	AuthToken       string                 `protobuf:"bytes,3,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	BootstrappedAt  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=bootstrapped_at,json=bootstrappedAt,proto3" json:"bootstrapped_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StoredIdentity) Reset() {
	*x = StoredIdentity{}
	mi := &file_vpn_agent_v1_stored_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredIdentity) ProtoMessage() {}

func (x *StoredIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_agent_v1_stored_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredIdentity.ProtoReflect.Descriptor instead.
func (*StoredIdentity) Descriptor() ([]byte, []int) {
	return file_vpn_agent_v1_stored_proto_rawDescGZIP(), []int{1}
}

func (x *StoredIdentity) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StoredIdentity) GetAgentInstanceId() string {
	if x != nil {
		return x.AgentInstanceId
	}
	return ""
}

func (x *StoredIdentity) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *StoredIdentity) GetBootstrappedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.BootstrappedAt
	}
	return nil
}

var File_vpn_agent_v1_stored_proto protoreflect.FileDescriptor

const file_vpn_agent_v1_stored_proto_rawDesc = "" +
	"\n" +
	"\x19vpn/agent/v1/stored.proto\x12\fvpn.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18vpn/agent/v1/agent.proto\"\xf1\x05\n" +
	"\x0fStoredPlacement\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x12&\n" +
	"\x0fbackend_node_id\x18\x05 \x01(\tR\rbackendNodeId\x12\x1d\n" +
	"\n" +
	"op_version\x18\x06 \x01(\x04R\topVersion\x12?\n" +
	"\rdesired_state\x18\a \x01(\x0e2\x1a.vpn.agent.v1.DesiredStateR\fdesiredState\x12?\n" +
	"\rapplied_state\x18\b \x01(\x0e2\x1a.vpn.agent.v1.AppliedStateR\fappliedState\x129\n" +
	"\ttransport\x18\t \x01(\x0e2\x1b.vpn.agent.v1.TransportKindR\ttransport\x122\n" +
	"\bprotocol\x18\n" +
	" \x01(\x0e2\x16.vpn.agent.v1.ProtocolR\bprotocol\x12\x1d\n" +
	"\n" +
	"is_revoked\x18\v \x01(\bR\tisRevoked\x12@\n" +
	"\vvalid_until\x18\f \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"validUntil\x88\x01\x01\x12>\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampH\x01R\tupdatedAt\x88\x01\x01\x12G\n" +
	"\x0flast_applied_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampH\x02R\rlastAppliedAt\x88\x01\x01\x12,\n" +
	"\x12entry_override_tag\x18\x0f \x01(\tR\x10entryOverrideTagB\x0e\n" +
	"\f_valid_untilB\r\n" +
	"\v_updated_atB\x12\n" +
	"\x10_last_applied_at\"\xb9\x01\n" +
	"\x0eStoredIdentity\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12*\n" +
	"\x11agent_instance_id\x18\x02 \x01(\tR\x0fagentInstanceId\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x03 \x01(\tR\tauthToken\x12C\n" +
	"\x0fbootstrapped_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0ebootstrappedAtB\xb8\x01\n" +
	"\x10com.vpn.agent.v1B\vStoredProtoP\x01ZEgithub.com/lannister-dev/go-node-agent/pkg/proto/vpn/agent/v1;agentv1\xa2\x02\x03VAX\xaa\x02\fVpn.Agent.V1\xca\x02\fVpn\\Agent\\V1\xe2\x02\x18Vpn\\Agent\\V1\\GPBMetadata\xea\x02\x0eVpn::Agent::V1b\x06proto3"

var (
	file_vpn_agent_v1_stored_proto_rawDescOnce sync.Once
	file_vpn_agent_v1_stored_proto_rawDescData []byte
)

func file_vpn_agent_v1_stored_proto_rawDescGZIP() []byte {
	file_vpn_agent_v1_stored_proto_rawDescOnce.Do(func() {
		file_vpn_agent_v1_stored_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vpn_agent_v1_stored_proto_rawDesc), len(file_vpn_agent_v1_stored_proto_rawDesc)))
	})
	return file_vpn_agent_v1_stored_proto_rawDescData
}

var file_vpn_agent_v1_stored_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vpn_agent_v1_stored_proto_goTypes = []any{
	(*StoredPlacement)(nil),       // 0: vpn.agent.v1.StoredPlacement
	(*StoredIdentity)(nil),        // 1: vpn.agent.v1.StoredIdentity
	(DesiredState)(0),             // 2: vpn.agent.v1.DesiredState
	(AppliedState)(0),             // 3: vpn.agent.v1.AppliedState
	(TransportKind)(0),            // 4: vpn.agent.v1.TransportKind
	(Protocol)(0),                 // 5: vpn.agent.v1.Protocol
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_vpn_agent_v1_stored_proto_depIdxs = []int32{
	2, // 0: vpn.agent.v1.StoredPlacement.desired_state:type_name -> vpn.agent.v1.DesiredState
	3, // 1: vpn.agent.v1.StoredPlacement.applied_state:type_name -> vpn.agent.v1.AppliedState
	4, // 2: vpn.agent.v1.StoredPlacement.transport:type_name -> vpn.agent.v1.TransportKind
	5, // 3: vpn.agent.v1.StoredPlacement.protocol:type_name -> vpn.agent.v1.Protocol
	6, // 4: vpn.agent.v1.StoredPlacement.valid_until:type_name -> google.protobuf.Timestamp
	6, // 5: vpn.agent.v1.StoredPlacement.updated_at:type_name -> google.protobuf.Timestamp
	6, // 6: vpn.agent.v1.StoredPlacement.last_applied_at:type_name -> google.protobuf.Timestamp
	6, // 7: vpn.agent.v1.StoredIdentity.bootstrapped_at:type_name -> google.protobuf.Timestamp
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_vpn_agent_v1_stored_proto_init() }
func file_vpn_agent_v1_stored_proto_init() {
	if File_vpn_agent_v1_stored_proto != nil {
		return
	}
	file_vpn_agent_v1_agent_proto_init()
	file_vpn_agent_v1_stored_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vpn_agent_v1_stored_proto_rawDesc), len(file_vpn_agent_v1_stored_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vpn_agent_v1_stored_proto_goTypes,
		DependencyIndexes: file_vpn_agent_v1_stored_proto_depIdxs,
		MessageInfos:      file_vpn_agent_v1_stored_proto_msgTypes,
	}.Build()
	File_vpn_agent_v1_stored_proto = out.File
	file_vpn_agent_v1_stored_proto_goTypes = nil
	file_vpn_agent_v1_stored_proto_depIdxs = nil
}
