// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: vpn/agent/v1/sync.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncReportEvent struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion       uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	EventId             string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	NodeId              string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	EmittedAt           *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=emitted_at,json=emittedAt,proto3" json:"emitted_at,omitempty"`
	SyncedCount         uint32                 `protobuf:"varint,5,opt,name=synced_count,json=syncedCount,proto3" json:"synced_count,omitempty"`
	ConfigVersion       *uint64                `protobuf:"varint,6,opt,name=config_version,json=configVersion,proto3,oneof" json:"config_version,omitempty"`
	InventoryHash       *string                `protobuf:"bytes,7,opt,name=inventory_hash,json=inventoryHash,proto3,oneof" json:"inventory_hash,omitempty"`
	InventoryCount      *uint64                `protobuf:"varint,8,opt,name=inventory_count,json=inventoryCount,proto3,oneof" json:"inventory_count,omitempty"`
	FullResyncCompleted bool                   `protobuf:"varint,9,opt,name=full_resync_completed,json=fullResyncCompleted,proto3" json:"full_resync_completed,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SyncReportEvent) Reset() {
	*x = SyncReportEvent{}
	mi := &file_vpn_agent_v1_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncReportEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncReportEvent) ProtoMessage() {}

func (x *SyncReportEvent) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_agent_v1_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncReportEvent.ProtoReflect.Descriptor instead.
func (*SyncReportEvent) Descriptor() ([]byte, []int) {
	return file_vpn_agent_v1_sync_proto_rawDescGZIP(), []int{0}
}

func (x *SyncReportEvent) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *SyncReportEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *SyncReportEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SyncReportEvent) GetEmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EmittedAt
	}
	return nil
}

func (x *SyncReportEvent) GetSyncedCount() uint32 {
	if x != nil {
		return x.SyncedCount
	}
	return 0
}

func (x *SyncReportEvent) GetConfigVersion() uint64 {
	if x != nil && x.ConfigVersion != nil {
		return *x.ConfigVersion
	}
	return 0
}

func (x *SyncReportEvent) GetInventoryHash() string {
	if x != nil && x.InventoryHash != nil {
		return *x.InventoryHash
	}
	return ""
}

func (x *SyncReportEvent) GetInventoryCount() uint64 {
	if x != nil && x.InventoryCount != nil {
		return *x.InventoryCount
	}
	return 0
}

func (x *SyncReportEvent) GetFullResyncCompleted() bool {
	if x != nil {
		return x.FullResyncCompleted
	}
	return false
}

type SyncReportAckEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	EmittedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=emitted_at,json=emittedAt,proto3" json:"emitted_at,omitempty"`
	Status        SyncReportAckStatus    `protobuf:"varint,5,opt,name=status,proto3,enum=vpn.agent.v1.SyncReportAckStatus" json:"status,omitempty"`
	Error         *string                `protobuf:"bytes,6,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncReportAckEvent) Reset() {
	*x = SyncReportAckEvent{}
	mi := &file_vpn_agent_v1_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncReportAckEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncReportAckEvent) ProtoMessage() {}

func (x *SyncReportAckEvent) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_agent_v1_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncReportAckEvent.ProtoReflect.Descriptor instead.
func (*SyncReportAckEvent) Descriptor() ([]byte, []int) {
	return file_vpn_agent_v1_sync_proto_rawDescGZIP(), []int{1}
}

func (x *SyncReportAckEvent) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *SyncReportAckEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *SyncReportAckEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SyncReportAckEvent) GetEmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EmittedAt
	}
	return nil
}

func (x *SyncReportAckEvent) GetStatus() SyncReportAckStatus {
	if x != nil {
		return x.Status
	}
	return SyncReportAckStatus_SYNC_REPORT_ACK_STATUS_UNSPECIFIED
}

func (x *SyncReportAckEvent) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_vpn_agent_v1_sync_proto protoreflect.FileDescriptor

const file_vpn_agent_v1_sync_proto_rawDesc = "" +
	"\n" +
	"\x17vpn/agent/v1/sync.proto\x12\fvpn.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18vpn/agent/v1/agent.proto\"\xbe\x03\n" +
	"\x0fSyncReportEvent\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x129\n" +
	"\n" +
	"emitted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\temittedAt\x12!\n" +
	"\fsynced_count\x18\x05 \x01(\rR\vsyncedCount\x12*\n" +
	"\x0econfig_version\x18\x06 \x01(\x04H\x00R\rconfigVersion\x88\x01\x01\x12*\n" +
	"\x0einventory_hash\x18\a \x01(\tH\x01R\rinventoryHash\x88\x01\x01\x12,\n" +
	"\x0finventory_count\x18\b \x01(\x04H\x02R\x0einventoryCount\x88\x01\x01\x122\n" +
	"\x15full_resync_completed\x18\t \x01(\bR\x13fullResyncCompletedB\x11\n" +
	"\x0f_config_versionB\x11\n" +
	"\x0f_inventory_hashB\x12\n" +
	"\x10_inventory_count\"\x8a\x02\n" +
	"\x12SyncReportAckEvent\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x129\n" +
	"\n" +
	"emitted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\temittedAt\x129\n" +
	"\x06status\x18\x05 \x01(\x0e2!.vpn.agent.v1.SyncReportAckStatusR\x06status\x12\x19\n" +
	"\x05error\x18\x06 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_errorB\xb6\x01\n" +
	"\x10com.vpn.agent.v1B\tSyncProtoP\x01ZEgithub.com/lannister-dev/go-node-agent/pkg/proto/vpn/agent/v1;agentv1\xa2\x02\x03VAX\xaa\x02\fVpn.Agent.V1\xca\x02\fVpn\\Agent\\V1\xe2\x02\x18Vpn\\Agent\\V1\\GPBMetadata\xea\x02\x0eVpn::Agent::V1b\x06proto3"

var (
	file_vpn_agent_v1_sync_proto_rawDescOnce sync.Once
	file_vpn_agent_v1_sync_proto_rawDescData []byte
)

func file_vpn_agent_v1_sync_proto_rawDescGZIP() []byte {
	file_vpn_agent_v1_sync_proto_rawDescOnce.Do(func() {
		file_vpn_agent_v1_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vpn_agent_v1_sync_proto_rawDesc), len(file_vpn_agent_v1_sync_proto_rawDesc)))
	})
	return file_vpn_agent_v1_sync_proto_rawDescData
}

var file_vpn_agent_v1_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vpn_agent_v1_sync_proto_goTypes = []any{
	(*SyncReportEvent)(nil),       // 0: vpn.agent.v1.SyncReportEvent
	(*SyncReportAckEvent)(nil),    // 1: vpn.agent.v1.SyncReportAckEvent
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(SyncReportAckStatus)(0),      // 3: vpn.agent.v1.SyncReportAckStatus
}
var file_vpn_agent_v1_sync_proto_depIdxs = []int32{
	2, // 0: vpn.agent.v1.SyncReportEvent.emitted_at:type_name -> google.protobuf.Timestamp
	2, // 1: vpn.agent.v1.SyncReportAckEvent.emitted_at:type_name -> google.protobuf.Timestamp
	3, // 2: vpn.agent.v1.SyncReportAckEvent.status:type_name -> vpn.agent.v1.SyncReportAckStatus
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_vpn_agent_v1_sync_proto_init() }
func file_vpn_agent_v1_sync_proto_init() {
	if File_vpn_agent_v1_sync_proto != nil {
		return
	}
	file_vpn_agent_v1_agent_proto_init()
	file_vpn_agent_v1_sync_proto_msgTypes[0].OneofWrappers = []any{}
	file_vpn_agent_v1_sync_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vpn_agent_v1_sync_proto_rawDesc), len(file_vpn_agent_v1_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vpn_agent_v1_sync_proto_goTypes,
		DependencyIndexes: file_vpn_agent_v1_sync_proto_depIdxs,
		MessageInfos:      file_vpn_agent_v1_sync_proto_msgTypes,
	}.Build()
	File_vpn_agent_v1_sync_proto = out.File
	file_vpn_agent_v1_sync_proto_goTypes = nil
	file_vpn_agent_v1_sync_proto_depIdxs = nil
}
