// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: vpn/agent/v1/upstream.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpstreamChangedPayload struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion        uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	EventId              string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	NodeId               string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	EmittedAt            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=emitted_at,json=emittedAt,proto3" json:"emitted_at,omitempty"`
	UpstreamNodeId       string                 `protobuf:"bytes,5,opt,name=upstream_node_id,json=upstreamNodeId,proto3" json:"upstream_node_id,omitempty"`
	UpstreamPublicDomain string                 `protobuf:"bytes,6,opt,name=upstream_public_domain,json=upstreamPublicDomain,proto3" json:"upstream_public_domain,omitempty"`
	UpstreamRealityIp    *string                `protobuf:"bytes,7,opt,name=upstream_reality_ip,json=upstreamRealityIp,proto3,oneof" json:"upstream_reality_ip,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpstreamChangedPayload) Reset() {
	*x = UpstreamChangedPayload{}
	mi := &file_vpn_agent_v1_upstream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamChangedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamChangedPayload) ProtoMessage() {}

func (x *UpstreamChangedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_agent_v1_upstream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamChangedPayload.ProtoReflect.Descriptor instead.
func (*UpstreamChangedPayload) Descriptor() ([]byte, []int) {
	return file_vpn_agent_v1_upstream_proto_rawDescGZIP(), []int{0}
}

func (x *UpstreamChangedPayload) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *UpstreamChangedPayload) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *UpstreamChangedPayload) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *UpstreamChangedPayload) GetEmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EmittedAt
	}
	return nil
}

func (x *UpstreamChangedPayload) GetUpstreamNodeId() string {
	if x != nil {
		return x.UpstreamNodeId
	}
	return ""
}

func (x *UpstreamChangedPayload) GetUpstreamPublicDomain() string {
	if x != nil {
		return x.UpstreamPublicDomain
	}
	return ""
}

func (x *UpstreamChangedPayload) GetUpstreamRealityIp() string {
	if x != nil && x.UpstreamRealityIp != nil {
		return *x.UpstreamRealityIp
	}
	return ""
}

type PoolChangedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	EmittedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=emitted_at,json=emittedAt,proto3" json:"emitted_at,omitempty"`
	Slots         []*PoolSlot            `protobuf:"bytes,5,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolChangedPayload) Reset() {
	*x = PoolChangedPayload{}
	mi := &file_vpn_agent_v1_upstream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolChangedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolChangedPayload) ProtoMessage() {}

func (x *PoolChangedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_agent_v1_upstream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolChangedPayload.ProtoReflect.Descriptor instead.
func (*PoolChangedPayload) Descriptor() ([]byte, []int) {
	return file_vpn_agent_v1_upstream_proto_rawDescGZIP(), []int{1}
}

func (x *PoolChangedPayload) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *PoolChangedPayload) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *PoolChangedPayload) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PoolChangedPayload) GetEmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EmittedAt
	}
	return nil
}

func (x *PoolChangedPayload) GetSlots() []*PoolSlot {
	if x != nil {
		return x.Slots
	}
	return nil
}

type PoolSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotIndex     uint32                 `protobuf:"varint,1,opt,name=slot_index,json=slotIndex,proto3" json:"slot_index,omitempty"`
	BackendNodeId string                 `protobuf:"bytes,2,opt,name=backend_node_id,json=backendNodeId,proto3" json:"backend_node_id,omitempty"`
	Addr          string                 `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
	Port          uint32                 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolSlot) Reset() {
	*x = PoolSlot{}
	mi := &file_vpn_agent_v1_upstream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolSlot) ProtoMessage() {}

func (x *PoolSlot) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_agent_v1_upstream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolSlot.ProtoReflect.Descriptor instead.
func (*PoolSlot) Descriptor() ([]byte, []int) {
	return file_vpn_agent_v1_upstream_proto_rawDescGZIP(), []int{2}
}

func (x *PoolSlot) GetSlotIndex() uint32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

func (x *PoolSlot) GetBackendNodeId() string {
	if x != nil {
		return x.BackendNodeId
	}
	return ""
}

func (x *PoolSlot) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *PoolSlot) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

var File_vpn_agent_v1_upstream_proto protoreflect.FileDescriptor

const file_vpn_agent_v1_upstream_proto_rawDesc = "" +
	"\n" +
	"\x1bvpn/agent/v1/upstream.proto\x12\fvpn.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdb\x02\n" +
	"\x16UpstreamChangedPayload\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x129\n" +
	"\n" +
	"emitted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\temittedAt\x12(\n" +
	"\x10upstream_node_id\x18\x05 \x01(\tR\x0eupstreamNodeId\x124\n" +
	"\x16upstream_public_domain\x18\x06 \x01(\tR\x14upstreamPublicDomain\x123\n" +
	"\x13upstream_reality_ip\x18\a \x01(\tH\x00R\x11upstreamRealityIp\x88\x01\x01B\x16\n" +
	"\x14_upstream_reality_ip\"\xd8\x01\n" +
	"\x12PoolChangedPayload\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x129\n" +
	"\n" +
	"emitted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\temittedAt\x12,\n" +
	"\x05slots\x18\x05 \x03(\v2\x16.vpn.agent.v1.PoolSlotR\x05slots\"y\n" +
	"\bPoolSlot\x12\x1d\n" +
	"\n" +
	"slot_index\x18\x01 \x01(\rR\tslotIndex\x12&\n" +
	"\x0fbackend_node_id\x18\x02 \x01(\tR\rbackendNodeId\x12\x12\n" +
	"\x04addr\x18\x03 \x01(\tR\x04addr\x12\x12\n" +
	"\x04port\x18\x04 \x01(\rR\x04portB\xba\x01\n" +
	"\x10com.vpn.agent.v1B\rUpstreamProtoP\x01ZEgithub.com/lannister-dev/go-node-agent/pkg/proto/vpn/agent/v1;agentv1\xa2\x02\x03VAX\xaa\x02\fVpn.Agent.V1\xca\x02\fVpn\\Agent\\V1\xe2\x02\x18Vpn\\Agent\\V1\\GPBMetadata\xea\x02\x0eVpn::Agent::V1b\x06proto3"

var (
	file_vpn_agent_v1_upstream_proto_rawDescOnce sync.Once
	file_vpn_agent_v1_upstream_proto_rawDescData []byte
)

func file_vpn_agent_v1_upstream_proto_rawDescGZIP() []byte {
	file_vpn_agent_v1_upstream_proto_rawDescOnce.Do(func() {
		file_vpn_agent_v1_upstream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vpn_agent_v1_upstream_proto_rawDesc), len(file_vpn_agent_v1_upstream_proto_rawDesc)))
	})
	return file_vpn_agent_v1_upstream_proto_rawDescData
}

var file_vpn_agent_v1_upstream_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_vpn_agent_v1_upstream_proto_goTypes = []any{
	(*UpstreamChangedPayload)(nil), // 0: vpn.agent.v1.UpstreamChangedPayload
	(*PoolChangedPayload)(nil),     // 1: vpn.agent.v1.PoolChangedPayload
	(*PoolSlot)(nil),               // 2: vpn.agent.v1.PoolSlot
	(*timestamppb.Timestamp)(nil),  // 3: google.protobuf.Timestamp
}
var file_vpn_agent_v1_upstream_proto_depIdxs = []int32{
	3, // 0: vpn.agent.v1.UpstreamChangedPayload.emitted_at:type_name -> google.protobuf.Timestamp
	3, // 1: vpn.agent.v1.PoolChangedPayload.emitted_at:type_name -> google.protobuf.Timestamp
	2, // 2: vpn.agent.v1.PoolChangedPayload.slots:type_name -> vpn.agent.v1.PoolSlot
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_vpn_agent_v1_upstream_proto_init() }
func file_vpn_agent_v1_upstream_proto_init() {
	if File_vpn_agent_v1_upstream_proto != nil {
		return
	}
	file_vpn_agent_v1_upstream_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vpn_agent_v1_upstream_proto_rawDesc), len(file_vpn_agent_v1_upstream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vpn_agent_v1_upstream_proto_goTypes,
		DependencyIndexes: file_vpn_agent_v1_upstream_proto_depIdxs,
		MessageInfos:      file_vpn_agent_v1_upstream_proto_msgTypes,
	}.Build()
	File_vpn_agent_v1_upstream_proto = out.File
	file_vpn_agent_v1_upstream_proto_goTypes = nil
	file_vpn_agent_v1_upstream_proto_depIdxs = nil
}
